# Generated by Django 4.0.1 on 2022-11-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toxicwords',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('Toxic_categorey', models.CharField(max_length=100)),
                ('Toxic_word', models.CharField(max_length=100)),
                ('Toxic_word_added_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Toxic_words_Details',
            },
        ),
    ]
