# Generated by Django 4.0.1 on 2022-11-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_warn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warn',
            name='user_status',
            field=models.CharField(default='unseen', max_length=100, null=True),
        ),
    ]
