# Generated by Django 4.0.1 on 2022-11-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_alter_post_toxic_status'),
        ('adminapp', '0006_warn_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warn',
            name='warn_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.post'),
        ),
    ]
