# Generated by Django 4.0.1 on 2022-10-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_display_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_date_of_birth', models.DateField()),
                ('user_contact', models.CharField(max_length=15)),
                ('user_city', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='images/user')),
                ('user_status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
    ]
