# Generated by Django 4.0.1 on 2022-10-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_desc', models.TextField()),
                ('feed_rating', models.CharField(default='0', max_length=100)),
                ('feedback_sentiment', models.CharField(max_length=50)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to='userapp.usermodel')),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
