# Generated by Django 4.1.2 on 2022-10-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_image', models.ImageField(upload_to='images/post')),
                ('post_desc', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_details',
            },
        ),
    ]
