# Generated by Django 4.1.2 on 2022-10-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='userapp.usermodel'),
        ),
    ]
