# Generated by Django 4.1.2 on 2022-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_i_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i_profile',
            name='i_Job_field',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='i_profile',
            name='i_food_taste',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='i_profile',
            name='i_hobbies',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='i_profile',
            name='i_personality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='i_profile',
            name='i_sports',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
