# Generated by Django 4.1.2 on 2022-10-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_i_profile_i_job_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Matching',
            fields=[
                ('matching_id', models.AutoField(primary_key=True, serialize=False)),
                ('matching_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'profile_matching_Details',
            },
        ),
    ]
