# Generated by Django 4.1.2 on 2022-10-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_profile_matching_matching_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_Request',
            fields=[
                ('friend_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('friend_request_status', models.CharField(default='Sent', max_length=100)),
                ('friend_request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
        ),
    ]
