# Generated by Django 4.1.2 on 2022-10-21 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='friend_request_other_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recive_request', to='userapp.usermodel'),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='friend_request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_send_request', to='userapp.usermodel'),
        ),
    ]
