# Generated by Django 4.1.2 on 2022-10-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_friend_request_friend_request_other_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_request',
            old_name='friend_request_other_user',
            new_name='reciver',
        ),
        migrations.RenameField(
            model_name='friend_request',
            old_name='friend_request_user',
            new_name='sender',
        ),
    ]
