# Generated by Django 4.0.1 on 2022-11-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(related_name='likes', to='userapp.UserModel'),
        ),
    ]
