# Generated by Django 4.0.1 on 2022-11-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_post_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Detection',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('converted_text', models.TextField()),
                ('toxic_status', models.CharField(max_length=10)),
                ('uploaded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_user', to='userapp.usermodel')),
            ],
            options={
                'db_table': 'audio_detection_details',
            },
        ),
    ]
