# Generated by Django 4.0.1 on 2022-11-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_post_post_audio_alter_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='converted_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='toxic_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
