# Generated by Django 4.0.1 on 2022-11-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_post_converted_text_post_toxic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='converted_text',
            field=models.TextField(null=True),
        ),
    ]
