# Generated by Django 4.0.1 on 2022-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_alter_post_toxic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='toxic_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
