# Generated by Django 4.0.1 on 2022-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_alter_post_toxic_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio_converstion',
            fields=[
                ('audio_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='audio/converstion')),
            ],
            options={
                'db_table': 'audio_converstion',
            },
        ),
    ]
