# Generated by Django 4.0.1 on 2022-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_audio_converstion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_video',
            field=models.FileField(null=True, upload_to='video/post'),
        ),
    ]
